import type { Lang } from '../../i18n/LanguageContext';

/** All simulator UI strings, per language. Business data (prices, volumes) lives in types.ts. */
export const simulatorContent = {
  fr: {
    steps: {
      service: 'Type de service',
      bien: 'Type de bien',
      volume: 'Volume à débarrasser',
      accessibilite: 'Accessibilité',
      objets: 'Objets à trier',
      localisation: 'Localisation',
      contact: 'Vos coordonnées',
      recap: 'Récapitulatif',
    },
    nav: {
      back: 'Retour',
      step: 'Étape',
      continue: 'Continuer',
    },
    serviceType: {
      title: 'Quel type de service recherchez-vous ?',
      subtitle: 'Sélectionnez la prestation qui correspond à votre besoin',
      types: {
        debarras: { label: 'Débarras simple', description: 'Vous souhaitez vider un logement, cave, garage ou grenier' },
        'debarras-nettoyage': { label: 'Débarras + Nettoyage', description: 'Débarras complet avec nettoyage final (optionnel) du logement' },
        succession: { label: 'Débarras succession', description: 'Intervention suite à un décès ou héritage' },
        demenagement: { label: 'Départ maison de retraite', description: "Vidage logement lors d'un départ en maison de retraite" },
        sinistre: { label: 'Nettoyage après sinistre', description: 'Remise en état après dégât des eaux, incendie...' },
      } as Record<string, { label: string; description: string }>,
    },
    bien: {
      title: 'Quel type de bien à débarrasser ?',
      subtitle: 'Sélectionnez le type de bien',
      types: {
        maison: { label: 'Maison', desc: 'Maison individuelle' },
        appartement: { label: 'Appartement', desc: 'Appartement individuel ou collectif' },
        cave: { label: 'Cave', desc: 'Sous-sol / espace de stockage' },
        grenier: { label: 'Grenier', desc: 'Combles / grenier' },
        garage: { label: 'Garage', desc: 'Garage individuel' },
        local: { label: 'Local professionnel', desc: 'Espace commercial / bureaux' },
      } as Record<string, { label: string; desc: string }>,
    },
    volume: {
      title: 'Quelle est la surface ou le volume ?',
      subtitle: 'Estimez la taille du bien à débarrasser',
      options: {
        studio: 'Studio', 't1-t2': 'T1 / T2', 't3-t4': 'T3 / T4', 't5+': 'T5 et plus',
        cave: 'Cave', grenier: 'Grenier', garage: 'Garage', local: 'Local',
      } as Record<string, string>,
      help: '1 m³ ≈ 5 cartons standards ou 1 électroménager volumineux',
    },
    accessibilite: {
      title: "L'accessibilité du bien",
      subtitle: "Précisez l'étage et l'accès au logement",
      etageLabel: 'Étage du bien',
      etageOptions: { rdc: 'RDC', '1': '1er étage', '2': '2e étage', '3': '3e étage et +' } as Record<string, string>,
      rdcDesc: 'Rez-de-chaussée',
      ascenseurLabel: 'Ascenseur disponible ?',
      ascenseurOui: 'Oui',
      ascenseurOuiDesc: 'Ascenseur disponible',
      ascenseurNon: 'Non',
      ascenseurNonDesc: 'Sans ascenseur',
      accessLabel: 'Accès général',
      accessOptions: {
        facile: 'Accès facile', difficile: 'Accès difficile', tres_difficile: 'Très difficile',
      } as Record<string, string>,
      accessDesc: {
        facile: 'Portes larges, passage dégagé', difficile: 'Escaliers étroits, tournants', tres_difficile: 'Spirale, hauteur, sous-sol',
      } as Record<string, string>,
    },
    objets: {
      title: "Quels types d'objets à débarrasser ?",
      subtitle: 'Sélectionnez les catégories présentes (plusieurs choix possibles)',
      labels: {
        electromenager: 'Électroménager', meubles: 'Meubles', vetements: 'Vêtements', livres: 'Livres',
        outillage: 'Outillage', bricolage: 'Matériaux/Bricolage', dechets: 'Déchets verts/encombrants', autres: 'Autres',
      } as Record<string, string>,
      help: 'Sélectionnez au moins une catégorie pour continuer',
    },
    localisation: {
      title: 'Où se trouve le bien ?',
      subtitle: 'Précisez la localisation pour le devis',
      villeLabel: 'Ville *',
      villePlaceholder: 'Ex: Fillinges, Annemasse...',
      cpLabel: 'Code postal *',
      help: 'Intervention en Haute-Savoie (74) et départements limitrophes',
      submit: 'Valider et continuer',
    },
    contact: {
      title: 'Vos coordonnées',
      subtitle: 'Pour vous envoyer votre devis gratuit',
      nomLabel: 'Nom complet',
      nomPlaceholder: 'Jean Dupont',
      emailLabel: 'Adresse e-mail',
      emailPlaceholder: 'jean.dupont@email.fr',
      telLabel: 'Téléphone',
      telPlaceholder: '06 12 34 56 78',
      note: 'Vos données sont protégées et ne seront utilisées que pour vous contacter concernant votre demande de devis.',
      submit: 'Voir mon devis estimatif',
    },
    recap: {
      title: 'Récapitulatif de votre demande',
      subtitle: 'Vérifiez les informations avant de valider',
      items: {
        service: 'Service', bien: 'Type de bien', volume: 'Volume estimé', etage: 'Étage',
        ascenseur: 'Ascenseur', acces: 'Accès', objets: 'Objets', localisation: 'Localisation',
        nom: 'Nom', email: 'E-mail', telephone: 'Téléphone',
      },
      bienLabels: {
        maison: 'Maison', appartement: 'Appartement', cave: 'Cave', grenier: 'Grenier',
        garage: 'Garage', local: 'Local professionnel',
      } as Record<string, string>,
      etageLabels: { rdc: 'RDC', '1': '1er étage', '2': '2e étage', '3': '3e étage et +' } as Record<string, string>,
      ascenseurLabels: { oui: 'Oui', non: 'Non' } as Record<string, string>,
      accessLabels: { facile: 'Accès facile', difficile: 'Accès difficile', tres_difficile: 'Très difficile' } as Record<string, string>,
      priceLabel: 'Devis estimatif',
      priceInfo: 'm³ × 55 €/m³',
      supplements: '(accès/étage)',
      horsValorisation: 'hors valorisation des biens',
      indicative: 'Estimation indicative, prix final confirmé par téléphone',
      note: "En validant, vous acceptez d'être contacté par Darkom-Debarras pour un devis gratuit. Aucune obligation d'engagement.",
      submit: 'Valider ma demande de devis',
    },
    complete: {
      title: 'Demande envoyée avec succès !',
      thanks: 'Merci',
      text1: 'Votre demande de devis pour',
      text2: 'a bien été enregistrée. Nous vous recontacterons sous 24h au',
      priceLabel: 'Estimation indicative',
      priceInfo: 'Prix final confirmé par téléphone',
      lieuLabel: 'Lieu :',
      emailLabel: 'E-mail :',
      restart: 'Nouvelle simulation',
    },
    sending: {
      title: 'Envoi en cours...',
      text: "Votre demande est en cours d'envoi, veuillez patienter.",
    },
    error: "Erreur lors de l'envoi. Veuillez réessayer.",
    retry: 'Réessayer',
  },
  en: {
    steps: {
      service: 'Type of service',
      bien: 'Type of property',
      volume: 'Volume to clear',
      accessibilite: 'Accessibility',
      objets: 'Items to sort',
      localisation: 'Location',
      contact: 'Your details',
      recap: 'Summary',
    },
    nav: {
      back: 'Back',
      step: 'Step',
      continue: 'Continue',
    },
    serviceType: {
      title: 'What type of service are you looking for?',
      subtitle: 'Select the service that matches your needs',
      types: {
        debarras: { label: 'Simple clearance', description: 'You want to empty a home, cellar, garage or loft' },
        'debarras-nettoyage': { label: 'Clearance + Cleaning', description: 'Full clearance with optional final clean of the property' },
        succession: { label: 'Estate clearance', description: 'Intervention following a death or inheritance' },
        demenagement: { label: 'Care home move', description: 'Clearing a home when someone moves into a care home' },
        sinistre: { label: 'Post-disaster clean-up', description: 'Restoration after water damage, fire...' },
      } as Record<string, { label: string; description: string }>,
    },
    bien: {
      title: 'What type of property needs clearing?',
      subtitle: 'Select the property type',
      types: {
        maison: { label: 'House', desc: 'Detached house' },
        appartement: { label: 'Flat', desc: 'Individual or collective flat' },
        cave: { label: 'Cellar', desc: 'Basement / storage space' },
        grenier: { label: 'Loft', desc: 'Attic / loft space' },
        garage: { label: 'Garage', desc: 'Private garage' },
        local: { label: 'Commercial premises', desc: 'Retail space / offices' },
      } as Record<string, { label: string; desc: string }>,
    },
    volume: {
      title: 'What is the size or volume?',
      subtitle: 'Estimate the size of the property to clear',
      options: {
        studio: 'Studio', 't1-t2': '1-2 rooms', 't3-t4': '3-4 rooms', 't5+': '5 rooms and up',
        cave: 'Cellar', grenier: 'Loft', garage: 'Garage', local: 'Commercial',
      } as Record<string, string>,
      help: '1 m³ ≈ 5 standard boxes or 1 bulky appliance',
    },
    accessibilite: {
      title: 'Accessibility of the property',
      subtitle: 'Specify the floor and access to the property',
      etageLabel: 'Floor',
      etageOptions: { rdc: 'Ground floor', '1': '1st floor', '2': '2nd floor', '3': '3rd floor and up' } as Record<string, string>,
      rdcDesc: 'Ground floor',
      ascenseurLabel: 'Is there a lift?',
      ascenseurOui: 'Yes',
      ascenseurOuiDesc: 'Lift available',
      ascenseurNon: 'No',
      ascenseurNonDesc: 'No lift',
      accessLabel: 'General access',
      accessOptions: {
        facile: 'Easy access', difficile: 'Difficult access', tres_difficile: 'Very difficult',
      } as Record<string, string>,
      accessDesc: {
        facile: 'Wide doors, clear passage', difficile: 'Narrow stairs, turns', tres_difficile: 'Spiral, height, basement',
      } as Record<string, string>,
    },
    objets: {
      title: 'What types of items need clearing?',
      subtitle: 'Select the categories present (multiple choices possible)',
      labels: {
        electromenager: 'Appliances', meubles: 'Furniture', vetements: 'Clothes', livres: 'Books',
        outillage: 'Tools', bricolage: 'Materials/DIY', dechets: 'Green waste/bulky items', autres: 'Other',
      } as Record<string, string>,
      help: 'Select at least one category to continue',
    },
    localisation: {
      title: 'Where is the property?',
      subtitle: 'Specify the location for the quote',
      villeLabel: 'Town *',
      villePlaceholder: 'e.g. Fillinges, Annemasse...',
      cpLabel: 'Postcode *',
      help: 'We work in Haute-Savoie (74) and neighbouring departments',
      submit: 'Validate and continue',
    },
    contact: {
      title: 'Your details',
      subtitle: 'So we can send you your free quote',
      nomLabel: 'Full name',
      nomPlaceholder: 'John Smith',
      emailLabel: 'Email address',
      emailPlaceholder: 'john.smith@email.com',
      telLabel: 'Phone',
      telPlaceholder: '06 12 34 56 78',
      note: 'Your data is protected and will only be used to contact you about your quote request.',
      submit: 'See my estimated quote',
    },
    recap: {
      title: 'Summary of your request',
      subtitle: 'Check the information before validating',
      items: {
        service: 'Service', bien: 'Property type', volume: 'Estimated volume', etage: 'Floor',
        ascenseur: 'Lift', acces: 'Access', objets: 'Items', localisation: 'Location',
        nom: 'Name', email: 'Email', telephone: 'Phone',
      },
      bienLabels: {
        maison: 'House', appartement: 'Flat', cave: 'Cellar', grenier: 'Loft',
        garage: 'Garage', local: 'Commercial premises',
      } as Record<string, string>,
      etageLabels: { rdc: 'Ground floor', '1': '1st floor', '2': '2nd floor', '3': '3rd floor and up' } as Record<string, string>,
      ascenseurLabels: { oui: 'Yes', non: 'No' } as Record<string, string>,
      accessLabels: { facile: 'Easy access', difficile: 'Difficult access', tres_difficile: 'Very difficult' } as Record<string, string>,
      priceLabel: 'Estimated quote',
      priceInfo: 'm³ × €55/m³',
      supplements: '(access/floor)',
      horsValorisation: 'before resale value deduction',
      indicative: 'Indicative estimate, final price confirmed by phone',
      note: 'By validating, you agree to be contacted by Darkom-Debarras for a free quote. No obligation.',
      submit: 'Submit my quote request',
    },
    complete: {
      title: 'Request sent successfully!',
      thanks: 'Thank you',
      text1: 'Your quote request for',
      text2: 'has been registered. We will contact you within 24h on',
      priceLabel: 'Indicative estimate',
      priceInfo: 'Final price confirmed by phone',
      lieuLabel: 'Location:',
      emailLabel: 'Email:',
      restart: 'New simulation',
    },
    sending: {
      title: 'Sending...',
      text: 'Your request is being sent, please wait.',
    },
    error: 'Error while sending. Please try again.',
    retry: 'Retry',
  },
} as const;

type FrContent = typeof simulatorContent.fr;
type EnContent = typeof simulatorContent.en;
export type SimulatorContent = Lang extends 'fr' ? FrContent : (FrContent | EnContent);
